# Create your own targets that compile the application

all:
	gcc -g -Wall main.c sensor_db.c -o main.out

all2:
	gcc -g -Wall ex2_remade.c -o main2.out

run: all
	./main.out

run2: all2
	./main2.out

